# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicati add-on
version: "1.0.0"
slug: duplicati
description: Duplicati add-on
url: "https://github.com/adrianoamalfi/ha-addons/tree/main/duplicati"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world duplicati..."
schema:
  message: "str?"
image: "ghcr.io/adrianoamalfi/{arch}-addon-duplicati"
