# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Duplicati add-on
version: "1.0.1"
slug: duplicati
description: Duplicati add-on
url: "https://github.com/adrianoamalfi/ha-addons/tree/main/duplicati"
arch:
  - armhf
  - amd64

ingress: true
ingress_port: 8200
ingress_stream: true
panel_icon: mdi:microsoft-visual-studio-code
startup: services
init: false
uart: true
hassio_api: true
hassio_role: manager
homeassistant_api: true

#webui: http://[HOST]:[PORT:8200]

map:
  - config:rw
  - ssl:rw
  - addons:rw
  - media:rw
  - share:rw
  - backup:rw
options:
  message: "Hello world duplicati..."
schema:
  message: "str?"
image: "ghcr.io/adrianoamalfi/{arch}-addon-duplicati"
